export * from './homework-9.js'
export * from './homework-8.js'
export * from './homework-7.js'
export * from './homework-6.js'
export * from './homework-5.js'
export * from './comments.js'
export * from './product-cards.js'
import './homework-10.js'